### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті.

### ISSUE THREAD

**Issue by vlnr70** [vlnr70/nrpk_OPI_2024#1]
Занайти найкраще фото.

**Comment by vlasnr** [comment]
Вже шукаю.

**Comment by vlasnr** [comment]
![image](https://github.com/user-attachments/assets/bcc05824-3873-4e11-b0f1-00d9f59d675d)

**Comment by vlasnr** [comment]
Завдання виконано.
